[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flashscore-scraper==0.0.7",
    "pandas>=2.3.2",
    "requests>=2.32.5",
]
